create database ecomm;
use ecomm;

alter table promotion
rename column `Promotion Id` to promotion_id;

alter table promotion
rename column `date` to eventdate;

-- Q1. What are the top 2 products (sub_category2) within each category based on the number of events?
 
select category, sub_category2, No_of_events from
(select category, sub_category2, count(*) as No_of_events, dense_rank() over(partition by category order by count(*) desc) as ranks from events
 group by category, sub_category2) as x
 where ranks <=2;



-- Q2. Find users whose number of events is higher than the average number of events generated by all users.
select distinct user_id, count(*) as no_of_events from events

group by user_id
having count(*) > (select overall_average from
							(select avg(no_of_events) as overall_average from
							(select distinct user_id, count(*) as no_of_events from events
							group by user_id) as x) as y);




-- Q3. Which products have user activity greater than the average activity of their category?

select * from
(select category, sub_category2, count(*) as user_activity from events
group by category, sub_category2)as z
inner join
(select category, round(avg(no_of_events),2) as average from
(select category, sub_category2, count(*) as no_of_events from events
group by category, sub_category2) as x
group by category) as y
on y.category = z.category
where user_activity > average;



-- Q4. What is the month-over-month change in user activity?

select *,(current_month_activity - prev_month_activity) as MOM_change_in_activity from
(select date_format(str_to_date(event_date, '%m/%d/%Y'), '%M') as Months, count(event_type) as current_month_activity, lag(count(event_type),1) over(order by month(str_to_date(event_date, '%m/%d/%Y')) asc ) as prev_month_activity from events
group by date_format(str_to_date(event_date, '%m/%d/%Y'), '%M'), month(str_to_date(event_date, '%m/%d/%Y'))) as x;




-- Q5. Which category had the highest month-over-month increase in activity?
-- LAG() + aggregation

select *,(current_month_activity - prev_month_activity) as MOM_change_in_activity from
(select category, date_format(str_to_date(event_date, '%m/%d/%Y'), '%M') as Months, count(event_type) as current_month_activity, 
lag(count(event_type),1) over(partition by category order by month(str_to_date(event_date, '%m/%d/%Y'))asc ) as prev_month_activity from events
group by category, date_format(str_to_date(event_date, '%m/%d/%Y'), '%M'), month(str_to_date(event_date, '%m/%d/%Y'))
) as x
where prev_month_activity is not null
order by  MOM_change_in_activity desc
limit 1;



-- Q6. Which users interacted with products from more than three different categories and what are those categories?

select distinct user_id, count(distinct category) as Category_interaction from events
group by user_id
having category_interaction > 3;




-- Q7.For each category, which product generated the highest number of events?


select category, sub_category2 from
(select category, sub_category2, count(*) as No_of_events, dense_rank() over(partition by category order by count(*) desc) as ranks from events
group by category, sub_category2) as x
where ranks = 1;



-- Q8. Which promoted products had the highest user activity on their promotion dates?

select distinct event_date, ProductId, COUNT(event_type) as user_activity_count from events
inner join promotion
on product_id = ProductId
and event_date = eventdate
group by productId, event_date, productid
order by user_activity_count desc
limit 1;

-- Q9. Which states had the highest user activity for promoted products on promotion date?

select state, count(event_type) as no_of_events from events as e
inner join promotion as p
on productid = product_id
and event_date = eventdate
group by state
order by no_of_events desc
limit 1

